import { Inter } from "next/font/google";

import Landing from "layouts/landing";
import Provider from "./_provider";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className={inter.className}>
        <Provider>
          <Landing>{children}</Landing>
        </Provider>
      </body>
    </html>
  );
}
